[project]
name = "search-tool"
version = "1.0.0"
dependencies = []

[project.scripts]
myterm = "myterm.myterm:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]